server {
    listen 80;
    server_name hdb-devops.fr www.hdb-devops.fr grafana.hdb-devops.fr prometheus.hdb-devops.fr;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name hdb-devops.fr www.hdb-devops.fr;

    ssl_certificate /etc/letsencrypt/live/grafana.hdb-devops.fr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/grafana.hdb-devops.fr/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;
}

server {
    listen 443 ssl;
    server_name grafana.hdb-devops.fr;

    ssl_certificate /etc/letsencrypt/live/grafana.hdb-devops.fr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/grafana.hdb-devops.fr/privkey.pem;

    location / {
        proxy_pass http://172.17.0.1:3000;
    }
}

server {
    listen 443 ssl;
    server_name prometheus.hdb-devops.fr;

    ssl_certificate /etc/letsencrypt/live/grafana.hdb-devops.fr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/grafana.hdb-devops.fr/privkey.pem;

    location / {
        proxy_pass http://172.17.0.1:9090;
    }
}